//go:build !ignore_autogenerated

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *OpenClawCABundleSpec) DeepCopyInto(out *OpenClawCABundleSpec) {
	*out = *in
}

func (in *OpenClawCABundleSpec) DeepCopy() *OpenClawCABundleSpec {
	if in == nil {
		return nil
	}
	out := new(OpenClawCABundleSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *OpenClawChromiumSpec) DeepCopyInto(out *OpenClawChromiumSpec) {
	*out = *in
	if in.Enabled != nil {
		out.Enabled = new(bool)
		*out.Enabled = *in.Enabled
	}
	out.Image = in.Image
}

func (in *OpenClawChromiumSpec) DeepCopy() *OpenClawChromiumSpec {
	if in == nil {
		return nil
	}
	out := new(OpenClawChromiumSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *OpenClawControlUISpec) DeepCopyInto(out *OpenClawControlUISpec) {
	*out = *in
	if in.AllowInsecureAuth != nil {
		out.AllowInsecureAuth = new(bool)
		*out.AllowInsecureAuth = *in.AllowInsecureAuth
	}
	if in.DangerouslyDisableDeviceAuth != nil {
		out.DangerouslyDisableDeviceAuth = new(bool)
		*out.DangerouslyDisableDeviceAuth = *in.DangerouslyDisableDeviceAuth
	}
}

func (in *OpenClawControlUISpec) DeepCopy() *OpenClawControlUISpec {
	if in == nil {
		return nil
	}
	out := new(OpenClawControlUISpec)
	in.DeepCopyInto(out)
	return out
}

func (in *OpenClawGatewaySpec) DeepCopyInto(out *OpenClawGatewaySpec) {
	*out = *in
	if in.TrustedProxies != nil {
		out.TrustedProxies = make([]string, len(in.TrustedProxies))
		copy(out.TrustedProxies, in.TrustedProxies)
	}
	if in.ControlUI != nil {
		out.ControlUI = new(OpenClawControlUISpec)
		in.ControlUI.DeepCopyInto(out.ControlUI)
	}
}

func (in *OpenClawGatewaySpec) DeepCopy() *OpenClawGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(OpenClawGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

func (in *OpenClawImageSpec) DeepCopyInto(out *OpenClawImageSpec) {
	*out = *in
}

func (in *OpenClawImageSpec) DeepCopy() *OpenClawImageSpec {
	if in == nil {
		return nil
	}
	out := new(OpenClawImageSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *OpenClawIngressSpec) DeepCopyInto(out *OpenClawIngressSpec) {
	*out = *in
	if in.Annotations != nil {
		out.Annotations = make(map[string]string, len(in.Annotations))
		for key, val := range in.Annotations {
			out.Annotations[key] = val
		}
	}
}

func (in *OpenClawIngressSpec) DeepCopy() *OpenClawIngressSpec {
	if in == nil {
		return nil
	}
	out := new(OpenClawIngressSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *OpenClawNode) DeepCopyInto(out *OpenClawNode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *OpenClawNode) DeepCopy() *OpenClawNode {
	if in == nil {
		return nil
	}
	out := new(OpenClawNode)
	in.DeepCopyInto(out)
	return out
}

func (in *OpenClawNode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *OpenClawNodeList) DeepCopyInto(out *OpenClawNodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]OpenClawNode, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *OpenClawNodeList) DeepCopy() *OpenClawNodeList {
	if in == nil {
		return nil
	}
	out := new(OpenClawNodeList)
	in.DeepCopyInto(out)
	return out
}

func (in *OpenClawNodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *OpenClawNodeSpec) DeepCopyInto(out *OpenClawNodeSpec) {
	*out = *in
	out.RuntimeSecretRef = in.RuntimeSecretRef
	out.Image = in.Image
	in.Gateway.DeepCopyInto(&out.Gateway)
	if in.Ingress != nil {
		out.Ingress = new(OpenClawIngressSpec)
		in.Ingress.DeepCopyInto(out.Ingress)
	}
	in.Storage.DeepCopyInto(&out.Storage)
	if in.CABundle != nil {
		out.CABundle = new(OpenClawCABundleSpec)
		in.CABundle.DeepCopyInto(out.CABundle)
	}
	if in.Chromium != nil {
		out.Chromium = new(OpenClawChromiumSpec)
		in.Chromium.DeepCopyInto(out.Chromium)
	}
}

func (in *OpenClawNodeSpec) DeepCopy() *OpenClawNodeSpec {
	if in == nil {
		return nil
	}
	out := new(OpenClawNodeSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *OpenClawNodeStatus) DeepCopyInto(out *OpenClawNodeStatus) {
	*out = *in
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}

func (in *OpenClawNodeStatus) DeepCopy() *OpenClawNodeStatus {
	if in == nil {
		return nil
	}
	out := new(OpenClawNodeStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *OpenClawRuntimeSecretRef) DeepCopyInto(out *OpenClawRuntimeSecretRef) {
	*out = *in
}

func (in *OpenClawRuntimeSecretRef) DeepCopy() *OpenClawRuntimeSecretRef {
	if in == nil {
		return nil
	}
	out := new(OpenClawRuntimeSecretRef)
	in.DeepCopyInto(out)
	return out
}

func (in *OpenClawStorageSpec) DeepCopyInto(out *OpenClawStorageSpec) {
	*out = *in
	if in.StorageClassName != nil {
		out.StorageClassName = new(string)
		*out.StorageClassName = *in.StorageClassName
	}
	if in.AccessModes != nil {
		out.AccessModes = make([]corev1.PersistentVolumeAccessMode, len(in.AccessModes))
		copy(out.AccessModes, in.AccessModes)
	}
}

func (in *OpenClawStorageSpec) DeepCopy() *OpenClawStorageSpec {
	if in == nil {
		return nil
	}
	out := new(OpenClawStorageSpec)
	in.DeepCopyInto(out)
	return out
}
